version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: App/api/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - GEMINI_API_KEY=
      - GROQ_API_KEY=
      - LLM_PROVIDER=
    volumes:
      - ./database:/app/database:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
